CREATE DATABASE RiwiAcademyDB;

USE RiwiAcademyDB;

CREATE TABLE STUDENT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    STATUS ENUM ("ACTIVE", "INACTIVE") NOT NULL
);

CREATE TABLE COURSE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    COURSE_NAME VARCHAR(100) UNIQUE NOT NULL,
    ID_STUDENT INT,
    FOREIGN KEY (ID_STUDENT) REFERENCES STUDENT (ID) ON DELETE CASCADE
);

CREATE TABLE REGISTRATION (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_COURSE INT,
    ID_STUDENT INT,
    FOREIGN KEY (ID_COURSE) REFERENCES COURSE (ID),
    FOREIGN KEY (ID_STUDENT) REFERENCES STUDENT (ID) ON DELETE CASCADE
);

CREATE TABLE GRADES (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    GRADE INT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    ID_COURSE INT,
    FOREIGN KEY (ID_COURSE) REFERENCES COURSE (ID)
);

SELECT * FROM GRADES;
